### ISSUE TITLE
Migrate Rating

### ISSUE THREAD

**Issue by Igloczek** [SnowdogApps/alpaca-ui#42]
https://alpaca-components-staging.herokuapp.com/components/detail/rating--default.html
https://alpaca-components-staging.herokuapp.com/components/detail/rating--rate.html

**Comment by jablpiotrek** [comment]
W dniu wt., 25.07.2023 o 17:16 Bartek Igielski ***@***.***>
napisał(a):

**Comment by Igloczek** [comment]
Towarzyszu @jablpiotrek, ale proszę nie spamować, zamknięte to zamknięte, proszę się rozjeść XD
