### ISSUE TITLE
Find a way to generate SVG Sprites on Webpack level

### ISSUE THREAD

**Issue by Igloczek** [SnowdogApps/alpaca-ui#6]
https://github.com/SnowdogApps/magento2-alpaca-components/blob/master/gulpfile.js#L205-L216

**Comment by bartdominiak** [comment]
We can use [svg-sprite-loader](https://github.com/kisenka/svg-sprite-loader) We've used that in snowdog-website project.

**Comment by Igloczek** [comment]
But... It will require to overwrite default Storybook Webpack config, since they already have some loader for SVG.

**Comment by bartdominiak** [comment]
Yeah. It's required to slice this config and add it again with required loader, as we did in Nuxt. Maybe there's another way to add, I'll check that.
